---
- name: Install k8s related packages
  block:
    - name: Add gpg key
      ansible.builtin.apt_key:
        url: https://pkgs.k8s.io/core:/stable:/{{ k8s_install_version }}/deb/Release.key
    - name: Add k8s apt repository
      ansible.builtin.apt_repository:
        repo: deb https://pkgs.k8s.io/core:/stable:/{{ k8s_install_version }}/deb/ /
    - name: Update apt repository
      ansible.builtin.apt:
        update_cache: true
    - name: Install kubectl
      ansible.builtin.apt:
        name: kubectl
        state: present

- name: Copy Kind configuration
  ansible.builtin.template:
    src: kind-config.yaml.j2
    dest: /tmp/kind-config.yaml
    mode: "0644"

- name: Check whether kind binary is already installed
  ansible.builtin.stat:
    path: "/usr/local/bin/kind"
  register: kind_binary

- name: Download kind binary
  ansible.builtin.get_url:
    url: https://kind.sigs.k8s.io/dl/v0.31.0/kind-linux-amd64
    dest: "/usr/local/bin/kind"
    mode: "0755"
    force: false
  when: not kind_binary.stat.exists

- name: Ensure kind binary is executable
  ansible.builtin.file:
    path: "/usr/local/bin/kind"
    mode: "0755"
  when: kind_binary.stat.exists

- name: Check if Kind cluster already exists
  ansible.builtin.command: /usr/local/bin/kind get clusters -q
  register: kind_clusters
  changed_when: false
  failed_when: false

- name: Create Kind cluster
  become: true
  ansible.builtin.command:
    cmd: /usr/local/bin/kind create cluster --config /tmp/kind-config.yaml
  changed_when: false
  when: "'kind' not in kind_clusters.stdout"

- name: Switch to legacy iptables
  vars:
    kind_legacy: false
  when: kind_legacy | default(false)
  block:
    - name: Enable legacy iptables alternatives on the host
      ansible.builtin.shell: |
        update-alternatives --set iptables /usr/sbin/iptables-legacy
        update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
      changed_when: false
    - name: Restart Docker service
      ansible.builtin.systemd:
        name: docker
        state: restarted

- name: Switch to nft iptables
  vars:
    kind_legacy:
  when: not (kind_legacy | default(false))
  block:
    - name: Enable nft iptables alternatives on the host
      ansible.builtin.shell: |
        update-alternatives --set iptables /usr/sbin/iptables-nft
        update-alternatives --set ip6tables /usr/sbin/ip6tables-nft
      changed_when: false
    - name: Restart Docker service
      ansible.builtin.systemd:
        name: docker
        state: restarted
