---
- name: Install helm
  block:
    - name: Download get_helm.sh
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get_helm.sh
        mode: "0755"
    - name: Run get_helm.sh
      ansible.builtin.command: /tmp/get_helm.sh
      args:
        creates: /usr/local/bin/helm
      changed_when: false

- name: Check if Cilium is installed
  ansible.builtin.command: kubectl get -n cilium deploy cilium-operator
  register: components_cilium_installed
  changed_when: false
  failed_when: false
- name: Setup Cilium
  when: components_cilium_installed.rc != 0
  block:
    - name: Add Cilium chart repo
      ansible.builtin.shell: |
        helm repo add cilium https://helm.cilium.io/
        helm repo update
      changed_when: false
    - name: Copy Cilium values file to /tmp
      ansible.builtin.copy:
        src: cilium-vars.yaml
        dest: /tmp/cilium-vars.yaml
        mode: "0644"
    - name: Deploy Cilium
      ansible.builtin.shell: |
        helm upgrade --install cilium cilium/cilium --namespace cilium --create-namespace -f /tmp/cilium-vars.yaml
      changed_when: false
    - name: Restart pods
      ansible.builtin.shell:
        executable: /bin/bash
        cmd: |
          set -o pipefail
          kubectl get pods -o custom-columns=NAMESPACE:.metadata.namespace,NAME:.metadata.name,HOSTNETWORK:.spec.hostNetwork \
            --namespace cilium --no-headers=true | grep '<none>' | awk '{print "-n "$1" "$2}' | xargs -L 1 -r kubectl delete pod
      changed_when: false
      failed_when: false

- name: Deploy application manifests
  vars:
    components_pod_num: 1
    components_other_num: 0
  block:
    - name: Delete previous application manifests
      ansible.builtin.command: "kubectl delete -f {{ item }} --ignore-not-found=true"
      loop:
        - /tmp/client.yaml
        - /tmp/other.yaml
      changed_when: false
      failed_when: false
    - name: Render application manifests
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "0644"
      loop:
        - src: server.yaml.j2
          dest: /tmp/server.yaml
        - src: client.yaml.j2
          dest: /tmp/client.yaml
        - src: other.yaml.j2
          dest: /tmp/other.yaml
      changed_when: false
    - name: Deploy application manifests
      ansible.builtin.command: kubectl apply -f {{ item }}
      loop:
        - /tmp/server.yaml
        - /tmp/client.yaml
      changed_when: false
    - name: Deploy other application manifests
      ansible.builtin.command: kubectl apply -f /tmp/other.yaml
      when: components_other_num > 0
      changed_when: false

- name: Copy bench.sh to control plane home directory
  ansible.builtin.copy:
    src: bench.sh
    dest: /home/ubuntu/bench.sh
    mode: "0755"
