# kubeProxyReplacement: true
# k8sServiceHost: auto

# bgp:
#   masquerade: true
#   datapathMode: netkit
# enableIPv4BIGTCP: true
# loadBalancer:
#   mode: dsr
# bandwidthManager:
#   enabled: true
#   bbr: true
